###
GET http://localhost:3333/v1/garantias

###
GET http://localhost:3333/v1/garantias/68c586665ec28e07008ffdfb

###
POST http://localhost:3333/v1/garantias/
Content-Type: "application/json"

{
  "fname": "Marcelo",
  "lname": "Andrade",
  "keys": "3456, 6598",
  "item": "MC1500TF15",
  "status": "sent",
  "observations": "any"
}
###
PUT http://localhost:3333/v1/garantias/68c592c18d20f120c6a39642
Content-Type: "application/json"

{
  "fname": "Marcelo",
  "lnane": "Andrade",
  "keys": "3456, 6598",
  "item": "MC1500TF15",
  "status": "sent",
  "observations": "any"
}
###
DELETE http://localhost:3333/v1/garantias/68c586665ec28e07008ffdfb